# Generated by Django 3.2.9 on 2021-12-16 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portmanteau_app', '0002_auto_20211215_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='items', to='portmanteau_app.type'),
        ),
        migrations.AlterField(
            model_name='item',
            name='weather',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='portmanteau_app.weather'),
        ),
    ]
