# Generated by Django 3.2.9 on 2021-12-17 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portmanteau_app', '0003_auto_20211216_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='capsules',
        ),
        migrations.AddField(
            model_name='item',
            name='capsule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='portmanteau_app.capsule'),
        ),
    ]
